include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VivoStyle

VivoStyle_FILES = Tweak.xm VVSFlipCardView.m VVSVideoView.m
VivoStyle_CFLAGS = -fobjc-arc -Wno-deprecated-declarations -Wno-unused-variable
VivoStyle_FRAMEWORKS = UIKit CoreMotion QuartzCore AVFoundation CoreMedia

include $(THEOS)/makefiles/tweak.mk
